apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  namespace: redis
  labels:
    type: local
    app: redis
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /mnt/data
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  nodeAffinity:   # default nodeAffinity for all persistent volumes
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1
